# Generated by Django 2.0.7 on 2018-08-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180807_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events_Two',
            new_name='First_Event',
        ),
        migrations.RenameModel(
            old_name='Works_One',
            new_name='First_Work',
        ),
        migrations.RenameModel(
            old_name='Events_One',
            new_name='Second_Event',
        ),
        migrations.RenameModel(
            old_name='Works_Three',
            new_name='Second_Work',
        ),
        migrations.RenameModel(
            old_name='Events_Three',
            new_name='Third_Event',
        ),
        migrations.RenameModel(
            old_name='Works_Two',
            new_name='Third_Work',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
        migrations.RenameField(
            model_name='second_work',
            old_name='blurb_three',
            new_name='blurb_two',
        ),
        migrations.RenameField(
            model_name='second_work',
            old_name='quote_three',
            new_name='quote_two',
        ),
        migrations.RenameField(
            model_name='second_work',
            old_name='reviewer_three',
            new_name='reviewer_two',
        ),
        migrations.RenameField(
            model_name='second_work',
            old_name='thumb_three',
            new_name='thumb_two',
        ),
        migrations.RenameField(
            model_name='second_work',
            old_name='title_three',
            new_name='title_two',
        ),
        migrations.RenameField(
            model_name='third_work',
            old_name='blurb_two',
            new_name='blurb_three',
        ),
        migrations.RenameField(
            model_name='third_work',
            old_name='quote_two',
            new_name='quote_three',
        ),
        migrations.RenameField(
            model_name='third_work',
            old_name='reviewer_two',
            new_name='reviewer_three',
        ),
        migrations.RenameField(
            model_name='third_work',
            old_name='thumb_two',
            new_name='thumb_three',
        ),
        migrations.RenameField(
            model_name='third_work',
            old_name='title_two',
            new_name='title_three',
        ),
    ]
