# Generated by Django 2.0.7 on 2018-08-07 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180807_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='First_Event',
        ),
        migrations.DeleteModel(
            name='First_Work',
        ),
        migrations.DeleteModel(
            name='Second_Event',
        ),
        migrations.DeleteModel(
            name='Second_Work',
        ),
        migrations.DeleteModel(
            name='Third_Event',
        ),
        migrations.DeleteModel(
            name='Third_Work',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='category_one',
            new_name='title_1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='category_three',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='category_two',
            new_name='title_3',
        ),
        migrations.AddField(
            model_name='work',
            name='blurb_1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='blurb_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='blurb_3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='cover_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='cover_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='cover_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
