# Generated by Django 2.0.7 on 2018-08-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180807_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Novel',
        ),
    ]
