# Generated by Django 2.0.7 on 2018-08-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180807_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_1', models.CharField(max_length=50)),
                ('event_picture_1', models.ImageField(upload_to='')),
                ('description_1', models.TextField()),
                ('link_1', models.URLField()),
                ('event_2', models.CharField(max_length=50)),
                ('event_picture_2', models.ImageField(upload_to='')),
                ('description_2', models.TextField()),
                ('link_2', models.URLField()),
                ('event_3', models.CharField(max_length=50)),
                ('event_picture_3', models.ImageField(upload_to='')),
                ('description_3', models.TextField()),
                ('link_3', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Novella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50)),
                ('cover_1', models.ImageField(upload_to='')),
                ('blurb_1', models.TextField()),
                ('title_2', models.CharField(max_length=50)),
                ('cover_2', models.ImageField(upload_to='')),
                ('blurb_2', models.TextField()),
                ('title_3', models.CharField(max_length=50)),
                ('cover_3', models.ImageField(upload_to='')),
                ('blurb_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=50)),
                ('cover_1', models.ImageField(upload_to='')),
                ('blurb_1', models.TextField()),
                ('title_2', models.CharField(max_length=50)),
                ('cover_2', models.ImageField(upload_to='')),
                ('blurb_2', models.TextField()),
                ('title_3', models.CharField(max_length=50)),
                ('cover_3', models.ImageField(upload_to='')),
                ('blurb_3', models.TextField()),
            ],
        ),
    ]
