# Generated by Django 2.1.4 on 2018-12-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20181205_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_picture_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_picture_3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='blurb_2',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='blurb_3',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='cover_2',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='cover_3',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='blurb_2',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='blurb_3',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='cover_2',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='cover_3',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='novella',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='short',
            name='blurb_2',
        ),
        migrations.RemoveField(
            model_name='short',
            name='blurb_3',
        ),
        migrations.RemoveField(
            model_name='short',
            name='cover_2',
        ),
        migrations.RemoveField(
            model_name='short',
            name='cover_3',
        ),
        migrations.RemoveField(
            model_name='short',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='short',
            name='title_3',
        ),
    ]
