# Generated by Django 2.1.4 on 2018-12-09 22:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20181208_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short',
            name='blurb_1',
        ),
        migrations.AddField(
            model_name='cover',
            name='link_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='link_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novella',
            name='link_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='short',
            name='link_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='blurb_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='novella',
            name='blurb_1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
