# Generated by Django 2.1.4 on 2018-12-09 22:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20181209_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='author',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cover',
            name='blogger',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cover',
            name='podcaster',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
